---
# ============================================================
# demok8s / apps/expense-ui/base/serviceaccount.yaml
# ============================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-ui-sa
  namespace: expense-ui
  labels:
    app.kubernetes.io/name: expense-ui
automountServiceAccountToken: false
